### ISSUE TITLE
The license is incorrect, MIT may not be used since this is based on GPL'ed code.

### ISSUE THREAD

**Issue by Nasa62** [itb-community/ftldat-rs#2]
Did you base this *solely* on examining ITB or FTL code (or other non-GPL code) and not on the open-source implementations in Slipstream Mod Manager or in AChurch's open-source SIL implementation that includes the FTL.dat parser? If so, both of those sources are GPL'ed which means this would also have to be GPL.

Just want to make sure because having a reverse engineered non-GPL'ed source would be nice for other projects.

**Comment by Nasa62** [comment]
Actually I see in Issue #1 you point out you have looked at SMM's code for this https://github.com/itb-community/ftldat-rs/issues/1#issuecomment-1331254452

So this needs to be GPLv3-licensed and not MIT licensed.... :cry: 

updated issue title.

**Comment by kartoFlane** [comment]
You're right, I didn't pay enough attention to SMM's own license and marked this project as MIT - I'll address that soon.

**Comment by Nasa62** [comment]
Also myself and some others reviewed SMM's license (a few people working on an update to it) and technically SMM is licensed wrong. It's based on GPLv3 code but is licensed as GPLv2 (with the "or newer license" clause) so it should all actually be GPLv3

**Comment by kartoFlane** [comment]
Updated license to GPLv3
